# Generated by Django 6.0.4 on 2026-04-15 18:19

from django.db import migrations


def seed_admin(apps, _):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('glambookapp', 'UserProfile')

    if not User.objects.filter(username='admin').exists():
        user = User.objects.create_superuser(
            username='admin',
            email='admin@glambook.com',
            password='admin',
        )
        UserProfile.objects.create(user=user, role='admin')


def reverse_seed_admin(apps, _):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('glambookapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_admin, reverse_seed_admin),
    ]
