# Generated by Django 6.0.4 on 2026-04-15 18:24

from django.db import migrations
from django.contrib.auth.hashers import make_password

# (group_name, role, username, first_name, last_name, email, password, is_staff)
USERS = [
    (
        "Customer",
        "customer",
        "customer1",
        "Customer",
        "One",
        "customer1@glambook.com",
        "customer1",
        False,
    ),
    (
        "Staff",
        "staff",
        "staff1",
        "Staff",
        "One",
        "staff1@glambook.com",
        "staff1",
        True,
    ),
    (
        "Admin", 
        "admin", 
        "admin", 
        "Admin", 
        "User", 
        "admin@glambook.com", 
        "admin", 
        True
    ),
]


def seed_groups_and_users(apps, _):
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")
    UserProfile = apps.get_model("glambookapp", "UserProfile")

    # Create the three groups
    customer_group, _ = Group.objects.get_or_create(name="Customer")
    staff_group, _ = Group.objects.get_or_create(name="Staff")
    admin_group, _ = Group.objects.get_or_create(name="Admin")

    group_map = {
        "Customer": customer_group,
        "Staff": staff_group,
        "Admin": admin_group,
    }

    for (
        group_name,
        role,
        username,
        first_name,
        last_name,
        email,
        password,
        is_staff,
    ) in USERS:
        if User.objects.filter(username=username).exists():
            user = User.objects.get(username=username)
            user.first_name = first_name
            user.last_name = last_name
            user.save()
        else:
            user = User(
                username=username,
                first_name=first_name,
                last_name=last_name,
                email=email,
                is_staff=is_staff,
                password=make_password(password),
            )
            user.save()
            UserProfile.objects.get_or_create(user=user, defaults={"role": role})

        user.groups.add(group_map[group_name])


def reverse_seed_groups_and_users(apps, _):
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")

    User.objects.filter(username__in=["customer1", "staff1"]).delete()
    Group.objects.filter(name__in=["Customer", "Staff", "Admin"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("glambookapp", "0002_seed_admin"),
    ]

    operations = [
        migrations.RunPython(seed_groups_and_users, reverse_seed_groups_and_users),
    ]
